package com.project.todo;

import org.springframework.ui.Model;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controller
//@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private TodoItemRepository todoItemRepository;

	@RequestMapping(path = "/")
	public String hello(Model model) {
		Iterable<TodoItem> itemListIterable = todoItemRepository.findAll();
		ArrayList<TodoItem> itemList = new ArrayList<>();
		itemListIterable.forEach(itemList::add);
		Collections.sort(itemList, new Comparator<TodoItem>() {
			@Override
			public int compare(TodoItem item1, TodoItem item2) {
				return Integer.compare(item2.getId(), item1.getId());
			}
		}); 
		
		model.addAttribute("name", "partner");
		model.addAttribute("todoItem", new TodoItem());
		model.addAttribute("itemList", itemList);
		return "hello";
	}

	@GetMapping(path = "/createTodoItem")
	public String createTodoItem(@ModelAttribute TodoItem todoItem, Model model) {
		todoItemRepository.save(todoItem);
		return hello(model);
	}
	
	@GetMapping(path = "/deleteTodoItem")
	public String deleteTodoItem(@ModelAttribute TodoItem todoItem, Model model) {
		System.out.println(todoItem);
		System.out.println(todoItem.getId());
		System.out.println(todoItem.getContent());
		todoItemRepository.delete(todoItem);
		return hello(model);
	}
	
	@GetMapping(path = "/editTodoItem")
	public String editTodoItem(@ModelAttribute TodoItem todoItem, Model model) {
		System.out.println(todoItem);
		System.out.println(todoItem.getId());
		System.out.println(todoItem.getContent());
		todoItemRepository.save(todoItem);
		return hello(model);
	}
}